name: Publish Web App CICD

on:
    push:
        branches:
            - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
        - name: Check out
          uses: actions/checkout@v4

        - name: Setup NodeJS ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with: 
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: npm install

        - name: Run the tests and generate coverage report
          run: npm test -- --coverage

        - name: Build application
          run: npm run build

        - name: Upload artifact to enable deployment
          uses: actions/upload-artifact@v4
          with:
            name: production-files
            path: ./dist
        
# Deploy Job
deploy:
  # Add a dependency to the build job
  needs: build
  # Specify runner + deployment step
  runs-on: ubuntu-latest
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./dist
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ ACTIONS_DEPLOY_ACCESS_TOKEN }}
        publish_dir: ./dist