name: Publish Web App CICD

on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
        - name: Check out
          uses: actions/checkout@v4

        - name: Setup NodeJS ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with: 
            node-version: ${{ matrix.node-version }}